version: '3.9'
services:
  bot:
    build: bot/
    container_name: ho-cyrhades-bot
    command: npm start
    healthcheck:
      test: ["CMD", "wscat", "-c", "ws://localhost:8282"]
      interval: 5s
      timeout: 3s
      retries: 10
  webserver:
    build: http/
    restart: always
    ports:
      - "80:80"
    container_name: ho-webserver
    command: npm start
    depends_on:
      bot:
        condition: service_healthy