version: '3.9'
services:
  ho-cyrhades-bot:
    build: ./.docker/bot/
    labels:
      ho.ctf.cyrhades: "1"
    command: npm start
    healthcheck:
      test: ["CMD", "wscat", "-c", "ws://localhost:8282"]
      interval: 5s
      timeout: 3s
      retries: 10
  ho-webserver:
    build: ./.docker/http/
    labels:
      ho.ctf.cyrhades: "1"
    environment:
      - HOOS_CTF_USERNAME=${HOOS_CTF_USERNAME:-}
    ports:
      - ${PORT}:80
    depends_on:
      ho-cyrhades-bot:
        condition: service_healthy